
import "./globals.css";
import { Inter } from 'next/font/google'
import GlobalProviders from "@/components/Application/GlobalProviders";
import { Toaster } from "@/components/ui/sonner";



const interFont = Inter({
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interFont.className} antialiased`}
      >
        <GlobalProviders>
          {children}
          <Toaster />
        </GlobalProviders>
      </body>
    </html>
  );
}
