
import { ToastContainer } from "react-toastify";
import "./globals.css";
import {Inter} from 'next/font/google'


const interFont = Inter({
  weight:['400','500','600','700','800'],
  subsets:['latin'],
  display:'swap'
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${interFont.className} antialiased`}
      >
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
